In [ ]:
from google.colab import files
files.upload()

Saving ht_data.csv to ht_data.csv


{'ht_data.csv': b'age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target\r\n57,1,3,145,233,1,0,150,0,2.3,0,0,1,1\r\n64,0,2,130,250,0,1,187,0,3.5,0,0,2,1\r\n52,1,1,130,204,0,0,172,0,1.4,2,0,2,1\r\n56,0,1,120,236,0,1,178,0,0.8,2,0,2,1\r\n66,0,0,120,354,0,1,163,1,0.6,2,0,2,1\r\n51,1,0,140,192,0,1,148,0,0.4,1,0,1,1\r\n42,0,1,140,294,0,0,153,0,1.3,1,0,2,1\r\n38,0,1,120,263,0,1,173,0,0,2,0,3,1\r\n72,0,2,172,199,1,1,162,0,0.5,2,0,3,1\r\n47,0,2,150,168,0,1,174,0,1.6,2,0,2,1\r\n55,0,0,140,239,0,1,160,0,1.2,2,0,2,1\r\n63,0,2,130,275,0,1,139,0,0.2,2,0,2,1\r\n64,0,1,130,266,0,1,171,0,0.6,2,0,2,1\r\n56,1,3,110,211,0,0,144,1,1.8,1,0,2,1\r\n41,1,3,150,283,1,0,162,0,1,2,0,2,1\r\n81,0,2,120,219,0,1,158,0,1.6,1,0,2,1\r\n70,0,2,120,340,0,1,172,0,0,2,0,2,1\r\n62,1,3,150,226,0,1,114,0,2.6,0,0,2,1\r\n56,1,0,150,247,0,1,171,0,1.5,2,0,2,1\r\n64,0,3,140,239,0,1,151,0,1.8,2,2,2,1\r\n56,0,0,135,234,0,1,161,0,0.5,1,0,3,1\r\n75,0,2,130,233,0,1,179,1,0.4,2,0,2,1\r\n69,0,0,140,226,0,1,178,0,

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("ht_data.csv")

In [ ]:
df.head(5)
df.isnull()
df1=df.dropna(axis=1,how='any')
df1.describe()


age            cp      trestbps          chol           fbs  \
count  26083.000000  26083.000000  26083.000000  26083.000000  26083.000000   
mean      55.661389      0.958594    131.592992    246.246061      0.149753   
std       15.189768      1.023931     17.588809     51.643522      0.356836   
min       11.000000      0.000000     94.000000    126.000000      0.000000   
25%       44.000000      0.000000    120.000000    211.000000      0.000000   
50%       56.000000      1.000000    130.000000    240.000000      0.000000   
75%       67.000000      2.000000    140.000000    275.000000      0.000000   
max       98.000000      3.000000    200.000000    564.000000      1.000000   

            restecg       thalach         exang       oldpeak         slope  \
count  26083.000000  26083.000000  26083.000000  26083.000000  26083.000000   
mean       0.526512    149.655024      0.326573      1.039512      1.400299   
std        0.525641     22.858109      0.468969      1.165138      0.616513   
min        0.000000     71.000000      0.000000      0.000000      0.000000   
25%        0.000000    133.000000      0.000000      0.000000      1.000000   
50%        1.000000    153.000000      0.000000      0.800000      1.000000   
75%        1.000000    166.000000      1.000000      1.600000      2.000000   
max        2.000000    202.000000      1.000000      6.200000      2.000000   

                 ca          thal        target  
count  26083.000000  26083.000000  26083.000000  
mean       0.721849      2.318752      0.547253  
std        1.011608      0.604659      0.497772  
min        0.000000      0.000000      0.000000  
25%        0.000000      2.000000      0.000000  
50%        0.000000      2.000000      1.000000  
75%        1.000000      3.000000      1.000000  
max        4.000000      3.000000      1.000000

In [ ]:
x=df1.iloc[:,1:12].values

In [ ]:
x[0:10]

array([[  3. , 145. , 233. ,   1. ,   0. , 150. ,   0. ,   2.3,   0. ,
          0. ,   1. ],
       [  2. , 130. , 250. ,   0. ,   1. , 187. ,   0. ,   3.5,   0. ,
          0. ,   2. ],
       [  1. , 130. , 204. ,   0. ,   0. , 172. ,   0. ,   1.4,   2. ,
          0. ,   2. ],
       [  1. , 120. , 236. ,   0. ,   1. , 178. ,   0. ,   0.8,   2. ,
          0. ,   2. ],
       [  0. , 120. , 354. ,   0. ,   1. , 163. ,   1. ,   0.6,   2. ,
          0. ,   2. ],
       [  0. , 140. , 192. ,   0. ,   1. , 148. ,   0. ,   0.4,   1. ,
          0. ,   1. ],
       [  1. , 140. , 294. ,   0. ,   0. , 153. ,   0. ,   1.3,   1. ,
          0. ,   2. ],
       [  1. , 120. , 263. ,   0. ,   1. , 173. ,   0. ,   0. ,   2. ,
          0. ,   3. ],
       [  2. , 172. , 199. ,   1. ,   1. , 162. ,   0. ,   0.5,   2. ,
          0. ,   3. ],
       [  2. , 150. , 168. ,   0. ,   1. , 174. ,   0. ,   1.6,   2. ,
          0. ,   2. ]])

In [ ]:
y=df1.target.values

In [ ]:
y[0:10]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.4)

In [ ]:
from sklearn import svm

In [ ]:
sv=svm.LinearSVC()
sv.fit(xtrain,ytrain)

LinearSVC()

In [ ]:
ypred=sv.predict(xtest)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy_score(ytest,ypred)

0.853459842821545

Using Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=100)
rf.fit(xtrain,ytrain)

RandomForestClassifier()

In [ ]:
ypred1=rf.predict(xtest)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [ ]:
confusion_matrix(ytest,ypred1)

array([[4732,    0],
       [   0, 5702]])

In [ ]:
accuracy_score(ytest,ypred1)

1.0

Logistic regression

In [ ]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(xtrain,ytrain)

LogisticRegression()

In [ ]:
ypred2=lr.predict(xtest)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [ ]:
confusion_matrix(ytest,ypred2)

array([[3653, 1079],
       [ 376, 5326]])

In [ ]:
accuracy_score(ytest,ypred2)

0.8605520414031053

DT

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(criterion='gini',max_depth=5)

In [ ]:
dt.fit(xtrain,ytrain)

DecisionTreeClassifier(max_depth=5)

In [ ]:
ypred3=dt.predict(xtest)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [ ]:
confusion_matrix(ytest,ypred3)

array([[3994,  738],
       [  65, 5637]])

In [ ]:
accuracy_score(ytest,ypred3)

0.9230400613379337